module.exports = {
  'post /socrata': 'register',
  'get /socrata': 'list',
  'get /socrata/:id': 'find',
  'get /socrata/:id/:item.:format': 'findResource',
  'get /socrata/:id/:item': 'findResource',
  'post /socrata/:id/:item': 'findResource',
  'get /socrata/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'get /socrata/:id/:item/FeatureServer/:layer': 'featureserver',
  'get /socrata/:id/:item/FeatureServer': 'featureserver',
  'post /socrata/:id/:item/FeatureServer/:layer/:method': 'featureserver',
  'post /socrata/:id/:item/FeatureServer/:layer': 'featureserver',
  'post /socrata/:id/:item/FeatureServer': 'featureserver',
  'get /socrata/:id/:item/thumbnail': 'thumbnail',
  'get /socrata/:id/:item/tiles/:z/:x/:y.:format': 'tiles',
  'delete /socrata/:id': 'del',
  'get /socrata/:id/:item/preview': 'preview',
  'get /socrata/:id/:item/drop': 'drop'
}
